# Generated by Django 5.2.5 on 2025-08-16 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата оплаты'),
        ),
    ]
