# Generated by Django 5.2.5 on 2025-08-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_checkout_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="checkout_url",
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
